public enum PasswordProtection {
    LOW, // MINIMUM OF LENGTH
    MEDIUM, // MINIMUM TWO TYPE OF CHARACTER
    STRONG, // MINIMUM ALL CHARACTER + LENGTH OF 12
    CRAZY // WOW MEN, MINIMUM ALL CHARACTER + LENGTH OF 20
}
